[versions]
coroutines = "1.6.4"
datetime = "0.4.0"
result = "1.1.17"
retry = "1.0.9"
detekt = "1.22.0"
hikari="5.0.1"
json = "1.5.0"
kotlin = "1.8.21"
ktor = "2.3.0"
sqlDelight = "1.5.5"
jib = "3.3.1"
mysql = "8.0.33"
logback = "1.4.7"
inline-logger = "1.0.5"
pi4j-core = "1.4"
pi4j-device = "1.3"
process = "1.4.1"
dsp = "2.4-1"
splitties = "3.0.0"
kinputevents = "-SNAPSHOT"

[libraries]
hikari = { module = "com.zaxxer:HikariCP", version.ref="hikari" }
io-gitlab-arturbosch-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
kotlin-inline-logger = { module = "com.michael-bull.kotlin-inline-logger:kotlin-inline-logger", version.ref = "inline-logger" }
kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "result" }
kotlin-result-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version.ref = "result" }
kotlin-retry = { module = "com.michael-bull.kotlin-retry:kotlin-retry", version.ref = "retry" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mysql-connector-java = { module = "mysql:mysql-connector-java", version.ref = "mysql" }
squareup-sqldelight-coroutine-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
squareup-sqldelight-jdbc-driver = { module = "com.squareup.sqldelight:jdbc-driver", version.ref = "sqlDelight" }
squareup-sqldelight-runtime-jvm = { module = "com.squareup.sqldelight:runtime-jvm", version.ref = "sqlDelight" }
pi4j-core = { module = "com.pi4j:pi4j-core", version.ref = "pi4j-core" }
pi4j-device = { module = "com.pi4j:pi4j-device", version.ref = "pi4j-device" }
github-pgreze-kotlin-process = { module = "com.github.pgreze:kotlin-process", version.ref = "process" }
github-axet-tarsosdsp = { module = "com.github.axet:TarsosDSP", version.ref = "dsp" }
louiscad-splitties-coroutines = { module = "com.louiscad.splitties:splitties-coroutines", version.ref = "splitties" }
github-treitmaier-kinputevents = { module = "com.github.treitmaier:KInputEvents", version.ref = "kinputevents" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
